cache:
  file:
    enabled: true
    max_age_hours: 24
    max_size_mb: 10
    path: lib/cache.json
daemon:
  enabled: true
  interval: 1
  interval_min: 1
integrations:
  dfir-iris:
    api_key: $IRSOAR_IRIS_API_KEY
    logging:
      log_level_file: info
      log_level_stdout: warning
      log_level_syslog: error
    default_severity: 3
    default_type: 2
    url: https://iris.pve.lan
    verify_certs: false
    version: 2.0.1
    webservice_name: ALERTELAST_API
  elastic_siem:
    elastic_password: $IRSOAR_ELASTIC_PW
    elastic_url: https://10.20.1.28:9200
    elastic_user: zsoar
    elastic_verify_certs: false
    enabled: true
    logging:
      log_level_file: debug
      log_level_stdout: warning
      log_level_syslog: error
  ibm_qradar:
    enabled: true
    logging:
      log_level_file: debug
      log_level_stdout: debug
      log_level_syslog: error
    qradar_api_key: $IRSOAR_QRADAR_API_KEY
    qradar_url: https://10.20.1.1
    qradar_verify_certs: false
  matrix_notify:
    enabled: true
    logging:
      log_level_file: info
      log_level_stdout: warning
      log_level_syslog: error
    matrix_access_token: $IRSOAR_MATRIX_ACCESS_TOKEN
    matrix_enabled: true
    matrix_server: $IRSOAR_MATRIX_SERVER_URL
    matrix_room_id: $IRSOAR_MATRIX_ROOM_ID
    matrix_verify_certs: true
  virus_total:
    api_key: $IRSOAR_VIRUSTOTAL_API_KEY
    enabled: true
    logging:
      log_level_file: info
      log_level_stdout: warning
      log_level_syslog: error
    verify_certs: false
logging:
  language: en
  log_file_rotate_size: 1
  log_file_split: false
  log_file_split_module: false
  log_file_split_start: true
  log_level_file: info
  log_level_stdout: warning
  log_level_syslog: none
  split_file_on_startup: true
  split_file_on_worker_iteration: false
  split_files_by_module: false
playbooks:
  PB_010_Generic_Elastic_Alerts:
    enabled: true
  PB_011_Generic_QRadar_Offenses:
    enabled: true
  PB_020_Generic_Suricata_Alerts:
    enabled: true
  PB_021_Advanced_Elastic_Context:
    enabled: true
  PB_022_Generic_NTOP-NG_Alerts:
    enabled: true
  PB_110_Generic_VirusTotal:
    enabled: true
  PB_900_Classify_and_Notify:
    enabled: true
setup:
  load_enviroment_variables: true
  setup_step: 2
